# Generated by Django 3.0.8 on 2020-12-02 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conselheiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ativo', models.CharField(max_length=15)),
                ('valor', models.DecimalField(decimal_places=3, max_digits=16)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 12, 2, 20, 54, 24, 990952))),
            ],
        ),
    ]
