# Generated by Django 3.0.8 on 2020-11-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conselheiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='periodo',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
