# Generated by Django 3.0.8 on 2020-12-02 21:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('conselheiro', '0002_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 21, 33, 4, 817275, tzinfo=utc)),
        ),
    ]
