# Generated by Django 3.0.8 on 2020-12-02 21:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('conselheiro', '0003_auto_20201202_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 21, 36, 36, 88174, tzinfo=utc)),
        ),
    ]
