# Generated by Django 3.0.8 on 2020-12-02 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conselheiro', '0004_auto_20201202_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
